services:

  # PlantUML Server / MCP
  plantuml:
    image: ${PLANTUML_IMAGE}:${PLANTUML_TAG}
    container_name: ${PLANTUML_NAME}
    restart: ${PLANTUML_POLICY}
    ports:
      - "${PLANTUML_PORT}:8080"